name: Deploy to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Cloudways API Access Token
        id: get_token
        run: |
          RESPONSE=$(curl -s -X POST "https://api.cloudways.com/api/v1/oauth/access_token" \
            -d "email=${{ secrets.CLOUDWAYS_EMAIL }}&api_key=${{ secrets.CLOUDWAYS_API_KEY }}")
          ACCESS_TOKEN=$(echo $RESPONSE | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Trigger Cloudways Git Pull
        run: |
          curl -X POST "https://api.cloudways.com/api/v1/git/pull" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "server_id": "'"${{ secrets.CLOUDWAYS_SERVER_ID }}"'",
              "app_id": "'"${{ secrets.CLOUDWAYS_APP_ID }}"'"
            }'
